Add a command to run uxterm in auto-night mode.
uxterm_night runs uxterm with a black background if it is before 6AM or
after 6PM

Modified checkupdates to not crash on non-arch linux systems (it prints
an error message and returns 0)

diff --git a/bin/checkupdates b/bin/checkupdates
--- a/bin/checkupdates
+++ b/bin/checkupdates
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/bin/bash
 #
 #   checkupdates: Safely print a list of pending updates.
 #
@@ -17,6 +17,11 @@
 #   You should have received a copy of the GNU General Public License
 #   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
+
+if [[ ! -f /usr/bin/pacman ]]; then
+	echo "Pacman not found: exiting." >&2
+	return 0
+fi
 
 declare -r myname='checkupdates'
 declare -r myver='1.4.0'
